apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
data:
  application.yml: |
    server:
      port: 8080
      servlet:
        encoding:
          charset: UTF-8
          enabled: true
          force: true
    spring:
      application:
        name: rocketmq-dashboard
    logging:
      config: classpath:logback.xml
    rocketmq:
      config:
        namesrvAddrs:
        - nameservice:9876
        isVIPChannel: true
        timeoutMillis:
        dataPath: /tmp/rocketmq-console/data
        enableDashBoardCollect: true
        msgTrackTopicName:
        ticketKey: ticket
        loginRequired: true
        useTLS: false
        accessKey: rocketmq2
        secretKey: 123456789
    threadpool:
      config:
        coreSize: 10
        maxSize: 10
        keepAliveTime: 3000
        queueSize: 5000
  role-permission.yml: |
    rolePerms:
      ordinary:
        - /rocketmq/*.query
        - /ops/*.query
        - /dashboard/*.query
        - /topic/*.query
        - /producer/*.query
        - /message/*.query
        - /messageTrace/*.query
        - /monitor/*.query
        - /consumer/*.query
        - /cluster/*.query
        - /dlqMessage/*.query
      administrator:
        - /rocketmq/*.query
        - /ops/*.query
        - /dashboard/*.query
        - /topic/*.query
        - /topic/sendTopicMessage.do
        - /producer/*.query
        - /message/*.query
        - /messageTrace/*.query
        - /monitor/*.query
        - /consumer/*.query
        - /cluster/*.query
        - /dlqMessage/*.query
        - /dlqMessage/exportDlqMessage.do
        - /dlqMessage/batchResendDlqMessage.do
  users.properties: |
    # This file supports hot reload. That is, when adding or modifying users, there is no need to restart the console.
    # Format: Each line defines one user, in the form of "username=password[,N]".
    # N is an optional item, which can be 0 (ordinary user); 1 (administrator).
    admin=12345678,1

    guest=12345678,0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-console
  template:
    metadata:
      labels:
        app: rocketmq-console
    spec:
      containers:
      - name: console
        env:
        - name: JAVA_OPTS
          value: -Dspring.config.location=/apps/data/console/config/
        image: registry.sensetime.com/sensecore-infra/rocketmq-dashboard:2.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /apps/data/console/config
          name: console-config
        - mountPath: /tmp/rocketmq-console/data/users.properties
          name: console-config
          subPath: users.properties
      dnsPolicy: ClusterFirst
      volumes:
      - configMap:
          defaultMode: 420
          name: console-config
        name: console-config