kubernetesClusterDomain: cluster.local
rocketmqOperator:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
    env:
      operatorName: rocketmq-operator
    image:
      repository: registry.sensetime.com/sensecore-infra/rocketmq-operator
      tag: v0.4.0_20250218T134345Z_d02bcb4a45
    imagePullPolicy: IfNotPresent
  replicas: 1
  serviceAccount:
    annotations: {}
