apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-console
  labels:
  {{- include "rocketmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: rocketmq-console
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
